;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Dec 16 2020
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
        ; Write your code here
	
	; CONTROL WORD 		SC1 SC2 RW1 RW2 M2 M1 M0 BCD
	
	MOV AL, 00110111B		; COUNTER 0, 16 BIT First LSByte then MSByte, MODE 3, BCD
	OUT 7EH, AL
	
	MOV AL, 01110111B		; COUNTER 1, 16BIT, MODE 3, BCD
	OUT 7EH, AL
	
	XOR AL, AL
	OUT 78H, AL			; 10 - 00, SENDING 00  TO COUNTER 0 SINCE LAST TWO VALUES ARE ZERO
	OUT 7AH, AL			; 05 - 00,  SENDING 00  TO COUNTER 1 SINCE LAST TWO VALUES ARE ZERO
	
	MOV AL, 10H			; SENDING 10 TO COUNTER 0 SINCE 10 - 00
	OUT 78H, AL
	
	MOV AL, 5H			; SENDING 05 TO COUNTER 0 SINCE 05 - 00
	OUT 7AH, AL
	
	
	
ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START